# Generated by Django 5.2.5 on 2025-09-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp', models.TextField()),
                ('en', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='tatoeba', max_length=32)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.wordmeaning')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meaning', 'source', 'source_id'), name='uq_example_by_sourceid')],
            },
        ),
    ]
